name: Deploy Org-Roam-UI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate and Deploy org-roam-ui
        uses: ikoamu/publish-org-roam-ui@main
        with:
          org-roam-db-filename: org-roam.db
          deploy-to-pages: true